### ISSUE TITLE
expand map extent

### ISSUE THREAD

**Issue by 7yl4r** [USF-IMARS/grafana-dashboards#7]
ABI images don't go far enough north

**Comment by dotis** [comment]
Can we change all images for the new FWC board to start at 24 Deg N? 23 seems a bit low and shows Cuba and other things that really aren't needed. Thanks.

**Comment by 7yl4r** [comment]
done

**Comment by dotis** [comment]
Much better. For some reason, the most recent images are not showing up. Is this just a delay with things getting onto ERDDAP?

**Comment by 7yl4r** [comment]
There shouldn't be much of a delay but I can't think of another reason besides ERDDAP.

**Comment by dotis** [comment]
Hmm. The recent images are still not showing up. 29th of April is the most recent. The new week's files just generated today, but I'm not sure what's going on with the early May ones. All the permissions are the same for each image.

**Comment by 7yl4r** [comment]
The parameter in datasets.xml that controls data reload frequency is called `ReloadEveryNMin` and by default is one week (10080 min).
We can set this lower to reduce the lag.
Were all of these newer files added within the last week?

**Comment by dotis** [comment]
Maybe. The 5 most recent 7day files are made every week on Tues. nights/Wed. mornings, but there is really only one truly "new" file created each week. The other 4 are re-written. Maybe we should increase it to once a day or once every two days, although going forward we should only get new files on Wed. am. I would like the new ones to appear fairly soon after they are created.
